### ISSUE TITLE
Variable indicating the number of trials done

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-client#14]
I am copy pasting the email text here:

Nico: We haven’t found the variable that indicates the number of trials done by one participant? Job_id, position, trial, all seem to indicate something else.

Sebastiaan: I looked at this, and it seems to me that you can simply sort the data by timestamp to see exactly when and how many trials were done. But maybe this isn't exactly what you meant. Can you clarify exactly what kind of information you need?

Nico: From experience we have found that sorting data by timestamp can be error prone, the time clock of a computer although mostly reliable can be changed and sometimes has random behaviour (when the connection is lost with the time server for instance). One of the great things of timestamping the trials from the server is that we will avoid a number of issues with timestamps. Still, keeping a separate account of the number of trials in an experiment has proved to be essential for us. Di you think we could implement that?

**Comment by smathot** [comment]
The attentional capture experiment now keeps track of an `n_jobs_done` variable as part of the generic session data. This variable simply increments with each job that is done, regardless of whether they are repitions, etc. Does that do the job?

**Comment by nclaidiere** [comment]
Ok thanks, yes, it does the job. I just wonder if this would not be useful on the server side of things but we will see. Cheers!
