### ISSUE TITLE
Variable with reward delivery

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-client#15]
Copy pasting email text here:

Nico: Is there a variable that indicates whether or not a reward has been delivered? There is a time_reward and count_reward variables but they are both NA (even when a reward is delivered).

Sebastiaan: This depends on how the experiment is implemented. In many cases, the variable 'correct' is used in a run-if statement to determine whether or not a reward was delivered. Is that what you mean?

Nico: Being correct and being rewarded can of course be two different things and its good to keep them separate, hence the count_reward variable? I agree that in most cases a correct response is followed by a reward, but we also have experiments with incorrect rewarded trials and with probabilistic rewards (80% correct rewarded for instance). Having a separate reward variable allow us to keep track of the number of rewards an individual has received independently of the conditions of the experiment. Does that make sense?

**Comment by smathot** [comment]
There is now a variable `omm_conditioner_action` that shows what the conditioner has done. For example, `reward+sound_both` would mean that a reward was delivered and both speakers were turned on.
