### ISSUE TITLE
Is there a way to show the mouse when OMM not connected?

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-client#18]
Is it possible to make the mouse cursor shown/hidden based on OMM connected?

**Comment by smathot** [comment]
Yes, but that's something related to the implementation of the experiment. I'm assuming that you're mostly interested in doing that for `touch_response` items, in which case you could edit the script and use a Python expression to determine whether the cursor should be shown or not:

```
set show_cursor "[='no' if 'omm' in globals() and omm.connected else 'yes']"
```
