### ISSUE TITLE
Temporary pool folders not removed

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-client#22]
Temporary `.opensesame_pool` folders in `AppData/Local/Temp` are not removed, as reported by @nclaidiere,  leading to the disk gradually filling up. This is due to `exp.pool.clean_up()` not being called because of the way in which experiments are executed by OMM. For now a workaround is to manually clean up the pool folder every once in a while.

**Comment by smathot** [comment]
This is fixed in OpenSesame 4.0.27, which cleans up left-over pool folders from previous instances.

**Comment by nclaidiere** [comment]
![Image](https://github.com/user-attachments/assets/8153a053-3416-4bf1-aabb-9c5f4a0ea26f)

**Comment by nclaidiere** [comment]
![Image](https://github.com/user-attachments/assets/42bd5eb6-d59d-4ba3-b94c-107b69bcf666)

**Comment by smathot** [comment]
They are indeed created, that's expected behavior. But they should be deleted when you close and then restart OpenSesame. Does that not happen?

**Comment by nclaidiere** [comment]
So, I did some more checking and here is what happens:
- when you open OS it creates a temp folder
- every time you do a trial it creates a new one
- when you close OS one disappear
- when you reopen OS there is a new one created

So on my system, with windows 11/OS4 the temp folders accumulate.

**Comment by smathot** [comment]
Before I look into this in more detail, can you confirm that you have updated to the latest version of OpenSesame using the automatic updater? This should have been fixed in 4.0.26. (The latest version is 4.0.37.)

**Comment by nclaidiere** [comment]
Indeed, I was using 4.0.24, my apologies, I will check with the latest version.

**Comment by nclaidiere** [comment]
Note that this is the version available from the OS website (that's why I thought I had the latest version). How do you get the version 37?

![Image](https://github.com/user-attachments/assets/52c31e8d-e2b9-446b-ab9a-631e9e18c290)

**Comment by smathot** [comment]
The automatic updater that is built into OpenSesame will allow you to update. Not all new versions are packaged, but rather you can update from within OpenSesame. If you start OpenSesame, you will get a notification after a while. (You have to be online for this, of course. If your system is not online, then you need first update it on a system that is online, and then transfer it.)

**Comment by nclaidiere** [comment]
Ok, I installed the new version (37) and checked, the folders are created during the experiment but then when OS is reopened after shutdown, they are removed. Thanks!
